openapi: 3.0.0
info:
  title: Survey API
  version: 1.0.0
paths:
  /api/survey:
    post:
      summary: Submit survey response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveyResponse'
      responses:
        '200':
          description: Response saved successfully
components:
  schemas:
    SurveyResponse:
      type: object
      properties:
        user_id:
          type: string
          description: Identifier for the user submitting the survey
        questions:
          type: object
          description: Object containing question IDs as keys and answers as comma-separated values
          additionalProperties:
            type: string
          example:
            question_1: "answer1, answer2"
            question_2: "answer3, answer4"